### ISSUE TITLE
cooler.io.create crashes: cannot exceed maximal size

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#107]
I want to save the pixels and the bins and I get the following error. I do not want to extend anything, I want to create a new cooler file with `cooler.io.create`. I do not really understand the error message. This happend using the file `Rao2014-GM12878-DpnII-allreps-filtered.1000kb.cool`. 

```
INFO:cooler:Writing pixels
Traceback (most recent call last):
  File "/home/wolffj/miniconda2/envs/hic_py3/bin/hicExport", line 7, in <module>
    main()
  File "/home/wolffj/miniconda2/envs/hic_py3/lib/python3.6/site-packages/hicexplorer/hicExport.py", line 243, in main
    hic_ma.save_cooler(args.outFileName)
  File "/home/wolffj/miniconda2/envs/hic_py3/lib/python3.6/site-packages/hicexplorer/HiCMatrix.py", line 1411, in save_cooler
    pixels=matrix_data_frame)
  File "/home/wolffj/miniconda2/envs/hic_py3/lib/python3.6/site-packages/cooler/io.py", line 237, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/home/wolffj/miniconda2/envs/hic_py3/lib/python3.6/site-packages/cooler/_writer.py", line 221, in write_pixels
    dset.resize((nnz + n,))
  File "/home/wolffj/miniconda2/envs/hic_py3/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 358, in resize
    self.id.set_extent(size)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "h5py/h5d.pyx", line 274, in h5py.h5d.DatasetID.set_extent (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5d.c:4252)
ValueError: Unable to set extend dataset (Dimension cannot exceed the existing maximal size (new: 8115676 max: 4850055))

```

//Edit
What I am doing: Open the cooler file, load matrix and bins to my data structure. I write then a new pandas frame for matrix and for the bins, and want to write it to a new cooler file with cooler.io.create. I am using Python 3.6. This crash does not happen if I convert the cooler file first to my own data format, close the software, and then I load my own data format file and save it to a cooler file. So I think there is some issue if a cooler file is opened and the data is more or less copied to a new cooler file. If you have any idea, help would be appreciated.

**Comment by nvictus** [comment]
This error occurs when your input contains more (upper triangle) pixels than the maximum that should occur for a matrix with `n` bins: `n * (n - 1) // 2 + n`. The usual culprit is duplicate pixels because the input records were not flipped according to chromosome order before aggregating. Or maybe you were loading a full symmetric matrix instead of just the upper triangle?

The error could be intercepted for a more useful error message.

**Comment by nvictus** [comment]
This will be less error-prone when #109 is implemented.
