### ISSUE TITLE
cooler-binning and pypairix issue

### ISSUE THREAD

**Issue by nandankita** [mirnylab/cooler#114]
After upgrading to 
```
cooler==0.7.8
pairsamtools==0.0.1.dev0
pypairix==0.3.5
```

Cooler binning (running with `distiller`) gives me this error:

```
Command error:
  + cooler cload pairix --nproc 8 --assembly assembly-name assembly.chrom.sizes:500000 file-R2.nodups.pairs.gz file-R2.500000.cool
  /home/an27w/lib/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to 
`np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
    from ._conv import register_converters as _register_converters
  INFO:cooler:Using 8 cores
  Traceback (most recent call last):
    File "/home/an27w/lib/miniconda3/bin/cooler", line 11, in <module>
      sys.exit(cli())
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/cooler/cli/cload.py", line 248, in pairix
      iterator = PairixAggregator(pairs_path, chromsizes, bins, map=map, n_chunks=max_split)
    File "/home/an27w/lib/miniconda3/lib/python3.6/site-packages/cooler/_binning.py", line 375, in __init__
      for c1, c2 in itertools.combinations(self.file_contigs):
  TypeError: Required argument 'r' (pos 2) not found
```

**Comment by nvictus** [comment]
Sorry, that bug was just introduced and missed in unit tests. Fixed it now. Also added the 0/1-based option to the indexed file loaders (`cooler cload pairix` and `tabix`). The default is now to assume 1-based. Can you try the latest master to verify all is solved?

**Comment by nandankita** [comment]
Thanks! Looks like it's running. Will tell you about 1 based fixed once it is finished.
