### ISSUE TITLE
behavior of create_cooler api function deviates from description: providing only custom columns requires 'count'

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/cooler#149]
API description here:
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L805
might be incorrect ...
when providing custom columns only, creation breaks during merging of unordered - seems like `count` must be included.
Ordered case seems to work fine, though.

### Long story:

while doing this for a cooler with a bunch of custom columns:
```python
# columns without 'count' ...
columns = ['custom_col1', 'custom_col2', ...]
cooler.create_cooler(output_path,
            clr.bins()[:],
            chunks, # iterator of pixel chunks ...
            columns=columns,
            # # should be float64 by default:
            # dtypes=dtypes,
            # to be included later ?!
            # # metadata : dict, optional
            # # assembly : str, optional
            ordered = False, # is it really ? should be
            symmetric_upper = True, # is it really ? should be
            mode = 'w')
```
this function:
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L596

breaks here:
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L655

I believe this is due to the fact that:
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L614
yields  custom columns ONLY , omitting `count`, which goes down to `CoolerMerger` in here:
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L667
and the "merger" creates aggregators only for the "custom"  columns:
https://github.com/mirnylab/cooler/blob/31fa2dc3d86865f2fb83ab35029729f9f06b6a80/cooler/reduce.py#L119
https://github.com/mirnylab/cooler/blob/31fa2dc3d86865f2fb83ab35029729f9f06b6a80/cooler/reduce.py#L120
 which in turn yields chunks of `pixels` with "custom"  columns ONLY, skipping `count` ...

Then I'm a bit blurry on what does `get_meta` do:
https://github.com/mirnylab/cooler/blob/eb9100642127fcd26682536794c851607d1f2f8c/cooler/util.py#L722

but it finally breaks here
https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L219

where I believe redefined columns are `count` + "custom"-ones, but the chunk returned by the "merger" does not have `count` anymore .....

actual error message is here:
```python
ating a Pool of 17 workers to tackle 609 tiles
cooler output ...
Traceback (most recent call last):
  File "/home/venevs/miniconda3/envs/dots-latest/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooltools/cli/call_dots.py", line 246, in call_dots
    nproc, score_dump_mode, verbose)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooltools/dotfinder.py", line 1115, in scoring_step
    mode = 'w')
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 921, in create_cooler
    max_merge=max_merge)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 656, in create_from_unordered
    columns=columns, dtypes=dtypes, mode='a', **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 565, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 219, in write_pixels
    n = len(chunk[columns[0]])
KeyError: 'count'

```

**Comment by nvictus** [comment]
Creation no longer requires a "count" column when custom value columns are given as substitutes. Works when creating from ordered and unordered input. Fixed in v0.8.3.
