### ISSUE TITLE
The sytle of chrom.size.

### ISSUE THREAD

**Issue by hzaumsq** [mirnylab/cooler#154]
when I use the cooler tools to binning ,I got the next error.
The code as following : cooler cload pairix /public/home/dxbo/msq/hic/chrom.size:100000 MiHic_S6_L001.output.pairs.gz 100k.cool

error:
NFO:cooler.cli.cload:Using 8 cores
Traceback (most recent call last):
  File "/public/home/dxbo/miniconda3/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/cooler/cli/cload.py", line 233, in pairix
    is_one_based=(not zero_based), n_chunks=max_split)
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/cooler/create/_ingest.py", line 695, in __init__
    f = pypairix.open(filepath, 'r')
pypairix.PairixError: Can't open the index file.

Then I try the next code ;
cooler cload pairix 1-based /public/home/dxbo/msq/hic/chrom.size:100000 MiHic_S6_L001.output.pairs.gz 100k.cool
it's also mkdir error.
so I want to ask for the proper type of the chrom.sizes file,and whant mistake I had made ?

**Comment by nvictus** [comment]
The chrom.sizes file should be UCSC-style: 2 columns, tab-separated (e.g. `chr1\t{length}`). The chromosomes should be ordered semantically (chr1, chr2, ... chrX, chrY, chrM) and not alphabetically.

I don't think there's anything wrong with your chromsizes file.

> pypairix.PairixError: Can't open the index file.

You seem to be missing the pairix index file. It should be named `MiHic_S6_L001.output.pairs.gz.px2` if your pairs file was indexed. If not, and you pairs file was properly prepared, you can index it with the [pairix](https://github.com/4dn-dcic/pairix) command line tool. 

Alternatively, you can use `cooler cload pairs` command to load an unindexed pairs file.
