### ISSUE TITLE
binning !cooler cload pairix

### ISSUE THREAD

**Issue by bio-lijs** [mirnylab/cooler#174]
when i used the cooler cload pairix to generate the matrix,it would had this erro.
`cooler cload pairix /scratch/bio-li/hic-test/chrsizes/hg38.mainonly.chrom.size:500000 /scratch/bio-lijs/hic-test/filtering/dedup_select_split/output.pairs.gz output.cool`
INFO:cooler.cli.cload:Using 8 cores
Traceback (most recent call last):
  File "/work/bio-lijs/miniconda3/envs/hic/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/cooler/cli/cload.py", line 233, in pairix
    is_one_based=(not zero_based), n_chunks=max_split)
  File "/work/bio-lijs/miniconda3/envs/hic/lib/python3.7/site-packages/cooler/create/_ingest.py", line 695, in __init__
    f = pypairix.open(filepath, 'r')
pypairix.PairixError: Can't open the index file.

**Comment by nvictus** [comment]
Your pairs file may not be indexed (see [pairix](https://github.com/4dn-dcic/pairix)), or the index may be stale. Alternatively, you can use [cooler cload **pairs**](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) to bin a non-indexed pairs file.

**Comment by nvictus** [comment]
Closing as this seems to have gone stale. Feel free to re-open if this wasn't resolved.
