### ISSUE TITLE
Unable to create cool file from sparse matrix

### ISSUE THREAD

**Issue by MarcoDiS** [mirnylab/cooler#206]
I'm trying to load a 10kb sparse matrix into .cool format file for visualization and analysis purposes. I would avoid re-analysing completely my dataset if possible. Here is my problem:
1 - Installation using conda has been done following the tutorial. No issue raised.
Python version 2.7 and h5py version 2.10.0
2 - For testing the input.tsv has a single line:
chr1	11830000	1180000	4200000	4210000	1
3 - chromosome_sizes.tsv has the line:
chr1	195471971
4 - the command line is:
cooler load chromosome_sizes.txt:10000 input.tsv test.cool -f bg2

I obtain this error:
INFO:cooler.cli.load:fields: {'end1': 2, 'count': 6, 'end2': 5, 'start2': 4, 'start1': 1, 'chrom1': 0, 'chrom2': 3}
INFO:cooler.cli.load:dtypes: {'end1': <type 'int'>, 'count': <type 'numpy.int32'>, 'end2': <type 'int'>, 'start2': <type 'int'>, 'start1': <type 'int'>, 'chrom1': <type 'str'>, 'chrom2': <type 'str'>}
INFO:cooler.cli.load:symmetric-upper: True
INFO:cooler.create:Writing chunk 0: tmpwhc0fU.multi.cool::0
Traceback (most recent call last):
  File "/home/user/.miniconda2/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/user/.miniconda2/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.miniconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/cooler/cli/load.py", line 334, in load
    h5opts=h5opts,
  File "/home/user/.miniconda2/lib/python2.7/site-packages/cooler/create/_create.py", line 690, in create_from_unordered
    create(uri, bins, chunk, columns=columns, dtypes=dtypes, mode="a", **kwargs)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/cooler/create/_create.py", line 563, in create
    with h5py.File(file_path, mode) as f:
  File "/home/user/.miniconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/user/.miniconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create

Any idea on what I'm doing wrong? Let me know should you need more info on the configuration of my system.

**Comment by nvictus** [comment]
Are you sure that's the entire error traceback? It looks like there should be more.

**Comment by MarcoDiS** [comment]
Yes, sorry
IOError: Unable to create file (unable to open file: name = '/scratch/devel/mstefano/2017_07_06_Project_with_Ralph_data/models_generation_using_IMP_5000bp/genes_for_Hossein/chr1_2000000_25000000_10kb/B_both_map_merged_conv_matrix_chr1_2000000_25000000bp/tmpwhc0fU.multi.cool', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by nvictus** [comment]
It says it is having trouble writing to the temp file because it already exists, which is strange, because it should be writing in append mode. Can you try to (1) make sure there are no junk temp files that didn't get deleted from a prior run, (2) upgrade to the latest version of cooler? If you can switch to a Python 3 environment, that would be even better.

Here's my reproduction. It completes successfully:

```sh
echo -e "chr1\t100000000" > test.chrom.sizes
echo -e "chr1\t1183000\t1180000\tchr1\t4200000\t4210000\t1" > test.bg2
cooler load test.chrom.sizes:10000 test.bg2 test.cool -f bg2
```

**Comment by MarcoDiS** [comment]
Thanks, switching to Python 3 solved my problem.
