### ISSUE TITLE
Error getting PairixAggregator

### ISSUE THREAD

**Issue by cmdcolin** [mirnylab/cooler#29]
Was wondering if the pairix library is needed for running? I did `pip install cooler` and then just ran `cooler` and it gave the error

```
cooler
Traceback (most recent call last):
  File "/home/cdiesh/.linuxbrew/bin/cooler", line 7, in <module>
    from cooler.cli import cli
  File "/home/cdiesh/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/cooler/cli/__init__.py", line 22, in <module>
    from . import (
  File "/home/cdiesh/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/cooler/cli/cload.py", line 16, in <module>
    from ..io import create, TabixAggregator, HDF5Aggregator, PairixAggregator
ImportError: cannot import name PairixAggregator

```

Does it need https://github.com/4dn-dcic/pairix ?

**Comment by nvictus** [comment]
Hey! Turns out this was actually due to a PyPI packaging problem where somehow stale source files got included in the build I made on Friday. Thanks for catching this! It seems to be fixed now.

The pairix library is not needed for running cooler, but we do plan to transition to that as the recommended indexing method for text contact list files over the tabix convention. Using it will require installing `pypairix`, which is also available via pip.
