### ISSUE TITLE
recursive_agg_onefile.py thows exception

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#38]
```
[peter@DBMI-PKerpedjiev-MacBook-Pro cooler.mirnylab] [origin-develop]$ python cooler/contrib/recursive_agg_onefile.py ~/data/test/su_test.cool
binsize: 1000000
total_length (bp): 3095693981
n_tiles: 12.0925546133
n_zooms: 4
Copying base matrix to level 4 and producing 4 new zoom levels counting down to 0...
ZoomLevel: 4 1000000
ZoomLevel: 3 2000000
Traceback (most recent call last):
  File "cooler/contrib/recursive_agg_onefile.py", line 191, in <module>
    aggregate(infile, outfile, n_zooms, chunksize, n_cpus)
  File "cooler/contrib/recursive_agg_onefile.py", line 72, in aggregate
    map=pool.imap if n_cpus > 1 else map)
TypeError: __init__() got an unexpected keyword argument 'cooler_root'
```

If I remove that parameter and re-run the script, I get this error:

```
[peter@DBMI-PKerpedjiev-MacBook-Pro cooler.mirnylab] [origin-develop]$ python cooler/contrib/recursive_agg_onefile.py ~/data/test/su_test.cool
binsize: 1000000
total_length (bp): 3095693981
n_tiles: 12.0925546133
n_zooms: 4
Copying base matrix to level 4 and producing 4 new zoom levels counting down to 0...
ZoomLevel: 4 1000000
ZoomLevel: 3 2000000
Traceback (most recent call last):
  File "cooler/contrib/recursive_agg_onefile.py", line 190, in <module>
    aggregate(infile, outfile, n_zooms, chunksize, n_cpus)
  File "cooler/contrib/recursive_agg_onefile.py", line 71, in aggregate
    map=pool.imap if n_cpus > 1 else map)
  File "/Users/peter/.virtualenvs/stuff/lib/python2.7/site-packages/cooler-0.6.4.dev0-py2.7.egg/cooler/io/_reader.py", line 374, in __init__
    self._size = cool.info['nnz']
AttributeError: 'str' object has no attribute 'info'
```

Running it on one of the files in the test directory yields yet another error:

```
[peter@DBMI-PKerpedjiev-MacBook-Pro cooler.mirnylab] [origin-develop]$ python cooler/contrib/recursive_agg_onefile.py tests/data/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool
Traceback (most recent call last):
  File "cooler/contrib/recursive_agg_onefile.py", line 180, in <module>
    binsize = cooler.info(f)['bin-size']
KeyError: 'bin-size'
```

**Comment by nvictus** [comment]
Fixed in 3851d61
