### ISSUE TITLE
ImportError: cannot import name 'PairixAggregator'

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#47]
Tried using cooler after updating it, here is the problem I get:
```
(Hi-C)[s1529682@login04(eddie) scripts]$ cooler
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/bin/cooler", line 11, in <module>
    load_entry_point('cooler==0.6.7.dev0', 'console_scripts', 'cooler')()
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/cli/__init__.py", line 34, in <module>
    from . import (
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/cli/cload.py", line 16, in <module>
    from ..io import create, TabixAggregator, HDF5Aggregator, PairixAggregator
ImportError: cannot import name 'PairixAggregator'
```
Am I missing anything?..

**Comment by nvictus** [comment]
How did you do the update? Pull from master, then pip?

**Comment by Phlya** [comment]
pip direcly form master

**Comment by nvictus** [comment]
Could there be stale byte code from the previous installation causing problems? Did you try uninstalling/reinstalling? I just tried `pip install git+git://github.com/mirnylab/cooler.git` and it seems to work.

**Comment by Phlya** [comment]
Indeed, seems to work after uninstalling first... Thanks, sorry for the false alarm :)
