### ISSUE TITLE
unhelpful error when file_contigs is empty

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooler#62]
```
INFO:cooler:Creating cooler at "out.cool::/"
INFO:cooler:Writing chroms
INFO:cooler:Writing bins
INFO:cooler:Writing pixels
Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cooler/cli/cload.py", line 243, in pairix
    create(cool_path, bins, iterator, metadata, assembly)
  File "/usr/local/lib/python3.5/dist-packages/cooler/io.py", line 237, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/usr/local/lib/python3.5/dist-packages/cooler/_writer.py", line 184, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/usr/local/lib/python3.5/dist-packages/cooler/_binning.py", line 455, in __iter__
    granges = balanced_partition(self.gs, self.n_chunks, self.file_contigs)
  File "/usr/local/lib/python3.5/dist-packages/cooler/_binning.py", line 74, in balanced_partition
    grouped = gs.bins.groupby('chrom', sort=False)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 4271, in groupby
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/groupby.py", line 1626, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/groupby.py", line 392, in __init__
    mutated=self.mutated)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/groupby.py", line 2625, in _get_grouper
    if is_categorical_dtype(gpr) and len(gpr) != len(obj):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/series.py", line 465, in __len__
    return len(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 2987, in __len__
    return len(self.items)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 2898, in _get_items
    return self.axes[0]
IndexError: list index out of range
```

**Comment by nvictus** [comment]
Fixed.
