### ISSUE TITLE
Error balancing zoomified cooler files

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#64]
Creating a balanced zoomified file using:

```
cooler zoomify --balance GSE93431_UNTR.1kb.cool.HDF5
```

leads to this error:

```
INFO:cooler:Balancing zoom level 0, bin size 16384000
Traceback (most recent call last):
  File "/Users/peter/.virtualenvs/env3/bin/cooler", line 11, in <module>
    load_entry_point('cooler', 'console_scripts', 'cooler')()
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/peter/.virtualenvs/env3/lib/python2.7/site-packages/cooler/cli/aggregate.py", line 249, in zoomify
    raise result.exception
KeyError: "Unable to open object (Object '16384000' doesn't exist)"
```

**Comment by pkerpedjiev** [comment]
Never mind, was using an older version of cooler. Ignore this issue please.
