### ISSUE TITLE
Provide explicit support for higlass mcool schema

### ISSUE THREAD

**Issue by hakanozadam** [mirnylab/cooler#68]
"cooler info" works on single resolution cooler files. But it doesn't work on multi-resolution cooler files.

 I ran "cooler zoomify" and generated a multi-resolution file for HiGlass. When I tried to read the metadata of that file using
cooler info myfilemulti.cool"

It gave me the following exception:

$ cooler info ~/U54-ESC4DN-FA-DpnII-2017524-R2-A.10000.multi.cool 
Traceback (most recent call last):
  File "/home/ozadamh/bin/miniconda3/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/cooler/cli/info.py", line 36, in info
    c = Cooler(cool_uri)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/cooler/api.py", line 78, in __init__
    _ct = chroms(grp)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/cooler/api.py", line 366, in chroms
    .append(pandas.Index(h5['chroms'].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
  File "/home/ozadamh/bin/miniconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-s_7obrrg-build/h5py/h5o.c:3734)
KeyError: "Unable to open object (Object 'chroms' doesn't exist)"

**Comment by nvictus** [comment]
You can use `cooler list -l` to list the zoom levels and their resolutions and e.g., `cooler info myfile.multi.cool::10`. Technically, the root group is not a cooler, but it is bad to have it error like that.

**Comment by nvictus** [comment]
For now, it seems better to display a helpful error listing all coolers inside a file when attempting to instantiate a `Cooler` object with an `.mcool`. This has been implemented.
