### ISSUE TITLE
cooler cload pairix failed (too many scaffolds?)

### ISSUE THREAD

**Issue by rdacemel** [mirnylab/cooler#76]
Hi! Congrats for the software. I have an overall good experience with it. 

However, when I try to run **cooler cload pairix** in the following datasets from Dudchenko et al 2017 doi: 10.1126/science.aal3327 on mosquito HiC it throws the following error:

`Command error:
  INFO:cooler:Using 10 cores
  /home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/cooler/_binning.py:382: UserWarning: Did not find contig  'aag2_ctg_3743' in contact list file.
    " '{}' in contact list file.".format(chrom))
  INFO:cooler:Creating cooler at "Aaegyptii_R1.20000.cool::/"
  INFO:cooler:Writing chroms
  INFO:cooler:Writing bins
  Traceback (most recent call last):
    File "/home/ska/rafa/programs/miniconda3/bin/cooler", line 11, in <module>
      sys.exit(cli())
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/cooler/cli/cload.py", line 243, in pairix
      create(cool_path, bins, iterator, metadata, assembly)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/cooler/io.py", line 222, in create
      write_bins(grp, bins, chroms['name'], h5opts)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/cooler/_writer.py", line 109, in write_bins
      **h5opts)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
      dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    File "/home/ska/rafa/programs/miniconda3/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 137, in make_new_dset
      dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
    File "h5py/h5d.pyx", line 79, in h5py.h5d.create (/tmp/pip-s_7obrrg-build/h5py/h5d.c:2136)
  ValueError: Unable to create dataset (Object header message is too large)
  .command.run.1: línea 99: 52082 Terminado               nxf_trace "$pid" .command.trace
`
Seems that that it may be related with the fragmented AaegL2 assembly of the mosquito genome in many scaffolds, but I'm not familiar at all with h5py. Cooler is being called internally by distiller-nf, that worked like charm till this very final step. The cooler call from distiller was the following:

```
cooler cload pairix         --nproc 10         --assembly AaegL2         AaegL2.filtered.fai:20000 Aaegyptii_R1.nodups.pairs.gz Aaegyptii_R1.20000
.cool
```

Any help is appreciated, since I'm really interested in running distiller and cooler on non-model organisms with somewhat scrambled genomes so I guess that I can experience this issue quite often. 

Thanks in advance,

Rafa.

**Comment by nandankita** [comment]
Hi,

I have encountered the same issue while running distiller. It fails on the binning step giving an error: ValueError: Unable to create dataset (Object header message is too large)

Thanks,
Ankita

**Comment by nvictus** [comment]
Thanks, Rafa and Ankita. So the issue is that `bins/chrom` (the chrom column of the bin table) is stored using the HDF5 [enum](http://docs.h5py.org/en/latest/special.html#special_dtype) data type: it's basically an integer column, with the actual enumeration dictionary stored in the dataset "header". It turns out that this header has a rather limited capacity. 

Fortunately, this isn't a huge problem because the enum was really just a convenience since we have the enumeration already stored in the `chroms` table. The solution would be to use a pure integer column instead of the enum one (that's the way we did it before) and make the enum optional. I'll set up a branch you can use to test it out.

**Comment by rdacemel** [comment]
Wow, that was fast!! Thanks a lot!

**Comment by nvictus** [comment]
Try out the `many-scaffolds` branch.

**Comment by rdacemel** [comment]
That solved it in my case, thank you very much!
