### ISSUE TITLE
Meta Data of Multi-resolution Cooler Files

### ISSUE THREAD

**Issue by hakanozadam** [mirnylab/cooler#78]
This is a very minor issue that I observed.

The metadata with the key "genome-assembly" switches to "unknown", from hg19, when  I generated multi-resolution cooler files with zoomify. 

As an example:
cooler info multires_balanced_coolers/ENCODE-HeLa-DpnII.1000
returns hg19 as the genome-asembly

When I generate a multires. cooler file using the above single resolution cooler file, and then query:

cooler info multires_balanced_coolers/ENCODE-HeLa-DpnII.1000.balanced.multires.cool::/1
The genome-assmebly was "unknown".

**Comment by Phlya** [comment]
Is it me, or does `cooler info` not work with multiresolution files at all?

```
s1529682:~/Datastore/wendy-lab/ilia/data/Hi-C/multicools$ cooler info serum_1Kb.multi.cool
Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cooler/cli/info.py", line 36, in info
    c = Cooler(cool_uri)
  File "/usr/local/lib/python3.5/dist-packages/cooler/api.py", line 78, in __init__
    _ct = chroms(grp)
  File "/usr/local/lib/python3.5/dist-packages/cooler/api.py", line 366, in chroms
    .append(pandas.Index(h5['chroms'].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-huypgcah-build/h5py/h5o.c:3734)
KeyError: "Unable to open object (Object 'chroms' doesn't exist)"
```

**Comment by hakanozadam** [comment]
You can try listing the single resolution cooler files first:

`cooler list serum_1Kb.multi.cool`

Then you can try getting the metadata for a particular resolution

`cooler info serum_1Kb.multi.cool::/1`

**Comment by Phlya** [comment]
Ah, yes, thanks a lot! Then I can confirm your bug report :) For the highest resolution it still shows the original assembly, though.

**Comment by nvictus** [comment]
This is solved by [cooler attrs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-attrs)
