### ISSUE TITLE
Index is out of bounds for axis 0

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#79]
Error when trying to run `cooler zoomify`

```
(cenv3) peter@MBI-CW-L10381:~/Downloads $ cooler zoomify h3k27ac_25kb.cool
INFO:cooler:Recursively aggregating "h3k27ac_25kb.cool"
INFO:cooler:Writing to "h3k27ac_25kb.multi.cool"
INFO:cooler:total_length (bp): 137547960
INFO:cooler:binsize: 25000
INFO:cooler:n_zooms: 5
INFO:cooler:quad tile cover: 32
INFO:cooler:Copying base matrix to level 5 and producing 5 new zoom levels counting down to 0...
INFO:cooler:Zoom level: 5 bin size: 25000
INFO:cooler:Aggregating at zoom level: 4 bin size: 50000
INFO:cooler:Creating cooler at "h3k27ac_25kb.multi.cool::/4"
INFO:cooler:Writing chroms
INFO:cooler:Writing bins
INFO:cooler:Writing pixels
Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/cenv3/bin/cooler", line 11, in <module>
    load_entry_point('cooler', 'console_scripts', 'cooler')()
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/peter/projects/cooler.mirnylab/cooler/cli/aggregate.py", line 234, in zoomify
    n_zooms, zoom_levels = multires_aggregate(cool_uri, outfile, nproc, chunksize, lock=lock)
  File "/Users/peter/projects/cooler.mirnylab/cooler/cli/aggregate.py", line 127, in multires_aggregate
    lock
  File "/Users/peter/projects/cooler.mirnylab/cooler/cli/aggregate.py", line 52, in aggregate
    append=True)
  File "/Users/peter/projects/cooler.mirnylab/cooler/io.py", line 237, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/Users/peter/projects/cooler.mirnylab/cooler/_writer.py", line 184, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/Users/peter/projects/cooler.mirnylab/cooler/_binning.py", line 549, in __iter__
    old_bin1_offset[c1] + step,
IndexError: index 5505 is out of bounds for axis 0 with size 5505
```

The source file was generated using hic2cool v0.3.6.

**Comment by nvictus** [comment]
Fixed in https://github.com/4dn-dcic/hic2cool/pull/11
