### ISSUE TITLE
Zoomify with variable bin size

### ISSUE THREAD

**Issue by aakashsur** [mirnylab/cooler#98]
I was analyzing a yeast dataset that used fragment sizes as the resolution instead of a set resolution. I used to the digest command, then csort, then cload, and everything works fine using the fragment bedfile. However, when I try to use the zoomify command, I get the following error: 

```
Traceback (most recent call last):

  File "/usr/local/bin/cooler", line 11, in <module>
   sys.exit(cli())

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cooler/cli/aggregate.py", line 367, in zoomify
    chunksize, lock=lock)

  File "/usr/local/lib/python2.7/dist-packages/cooler/cli/aggregate.py", line 79, in multires_aggregate
    n_zooms = get_quadtree_depth(clr.chromsizes, clr.binsize)

  File "/usr/local/lib/python2.7/dist-packages/cooler/cli/aggregate.py", line 66, in get_quadtree_depth
    tile_size_bp = QUAD_TILE_SIZE_PIXELS * binsize

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

I'm guessing zoomify fundamentally uses fixed resolutions and you can't coerce a variable bin size into a fixed one with the command. Any thoughts on how to proceed using built-in cooler commands?

**Comment by nvictus** [comment]
Yep, that's right. HiGlass doesn't support uneven bins yet. However, if you want to represent your map in fragment "units" you can hack that in my making a "pseudo" fixed-binsize matrix, either using fragment numbers, though I like to use the average fragment length rounded to the nearest kb as the fake bin size.

The easiest way to do this would be to dump the bins and pixels into two separate files (`cooler dump -t bins`, `cooler dump -t pixels`), modify the bins file appropriately, and then use `cooler cload -f coo <pseudobins> <pixels> <out.cool>`

**Comment by nvictus** [comment]
Closing this, but the coarsening of variable-sized bins is covered in #81.
